version: '3'
services:
    redis:
        container_name: redis
        image: lihn1011/redis:0.1
        volumes:
            - ./volumes/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
            - ./volumes/redis/data/:/data/

        restart: always
        ports:
            - "6379:6379"

    nginx:
        container_name: nginx
        image: lihn1011/nginx:0.4
        command: /bin/bash -c "/usr/sbin/nginx; /usr/sbin/php-fpm7.4; /usr/sbin/sshd;while true;do sleep 1 ; done"
        volumes:
            - ./volumes/nginx/config/default:/etc/nginx/sites-enabled/default
            - ../src/website/front_end/dist/:/var/www/html/
            - ../src/website/php/coin_view/:/var/www/html/coin_view/
        restart: always
        ports:
            - "80:80"
            - "443:443"

    trade:
        container_name: trade
        image: lihn1011/trade:0.1
        volumes:
            - ../src/collector/:/data/ 
        restart: always
        command: /bin/bash -c "cd /data/;  while true;do sleep 1 ; done"
        extra_hosts:
            - "api.huobi.pro:104.16.232.188"
            - "real.okex.com:104.19.212.87"
            - "api.hbdm.com:104.17.33.9"
        depends_on: 
            - redis

    mysql:
        container_name: mysql
        image: lihn1011/mysql:0.2
        volumes:
            - ./volumes/mysql/:/var/lib/mysql/

        restart: always
        command: mysqld --sql-mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
        expose:
            - 3306
        ports:
            - "6688:3306"

    history_scanner:
        container_name: history_scanner
        image: lihn1011/trade:0.1
        volumes:
            - ../src/collector/:/data/ 
        restart: always
        command: /bin/bash -c "cd /data/;  while true;do sleep 1 ; done"
        extra_hosts:
            - "api.huobi.pro:104.16.232.188"
            - "real.okex.com:104.19.212.87"
            - "api.hbdm.com:104.17.33.9"
        depends_on: 
            - redis
            - mysql